#This dockerfile allows the frontend service to run isolated without needing other containers for port forwarding
#The regular dockerfile uses proxy pass to named containers only
FROM node:18-alpine AS builder

WORKDIR /frontend
COPY package*.json /frontend/
RUN npm ci
COPY . /frontend/
RUN npm run build

FROM nginx:1.26-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /frontend/build/ /usr/share/nginx/html/
#Use a template file which allows for env variables
COPY nginx/nginx.conf.template /etc/nginx/nginx.conf.template
# Set the entrypoint to dynamically replace variables at runtime
CMD ["/bin/sh", "-c", "envsubst '${HOST_IP}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
#EXPOSE 80

