services:
  redis:
    image: redis:7.4-rc2-alpine
    networks: 
      - qnet
  pvws:
    build: ./pvws/docker
    environment:
      - EPICS_CA_ADDR_LIST=${EPICS_CA_ADDR_LIST}
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - PV_WRITE_SUPPORT=true
    network_mode: "host"
  python-server:
    build: ./python-server
    environment:
      - EPICS_CA_ADDR_LIST=${EPICS_CA_ADDR_LIST}
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - ZMQ_HOST=localhost
      - ZMQ_PORT=60625
    network_mode: "host"
  qserver:
    build: ./queue-server
    environment:
      - EPICS_CA_ADDR_LIST=${EPICS_CA_ADDR_LIST}
      - EPICS_CA_AUTO_ADDR_LIST=NO
    network_mode: "host"
    command: ["start-re-manager", "--zmq-publish-console", "ON", "--redis-addr", "127.0.0.1:6379", "--startup-dir", "/code/startup_bl531", "--keep-re"]
    depends_on:
      - redis
  qserver-api:
    build: ./queue-server-api
    environment:
      - QSERVER_HTTP_SERVER_ALLOW_ORIGINS=*
      - QSERVER_HTTP_SERVER_SINGLE_USER_API_KEY=test
    networks: 
      - qnet
    ports:
      - "60610:60610"
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "60610", "bluesky_httpserver.server:app"]
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - pvws
      - python-server
      - qserver-api
  
networks:
  qnet:
    driver: bridge

