authentication:
  single_user_api_key: ${TILED_OSPREY_API_KEY}
  allow_anonymous_access: true
uvicorn:
  host: 0.0.0.0
  port: 8003

trees:
  - path: /calibration
    tree: catalog
    args:
      uri: "sqlite:////mnt/data531/tiled/osprey/catalog.db" #change this
      writable_storage:
        - '/mnt/data531/tiled/osprey/storage'
        - 'sqlite:////mnt/data531/tiled/osprey/storage/tabular.db'
        #- "/mnt"
      readable_storage:
        - "/mnt/data531/tiled/storage"
        - "/mnt/data531/tiled/osprey/storage"
        - "/mnt"
      init_if_not_exists: true