authentication:
  single_user_api_key: ${TILED_SINGLE_USER_API_KEY}
  allow_anonymous_access: true
uvicorn:
  host: 0.0.0.0
  port: 8000
allow_origins:
  - http://192.168.10.155:5173
  - http://192.168.10.150:5173 
  - http://localhost:5173
  - http://localhost:5174
  - http://192.168.10.201:5173 
  - http://192.168.10.123:5173 
  - http://131.243.80.226:5173
  - http://192.168.10.100:5173
  - http://192.168.10.156:8080
  - http://192.168.10.156:4001
  - http://131.243.191.238:5173
  - http://localhost:8050
  - http://127.0.0.1:8050
# trees:
#   - path: /
#     tree: catalog
#     args:
#       uri: "sqlite:////home/bl531user/tiled_test/catalog.db"
#       writable_storage:
#         - '/home/bl531user/tiled_test/storage'
#         - 'sqlite:////home/bl531user/tiled_test/tabular.db'
#         - "/mnt"
#       readable_storage:
#         - "/home/bl531user/tiled_test/storage"
#         - "/mnt"
#       init_if_not_exists: true

# none of this is working, upgradfed tiled and no longer work
trees:
  - path: /
    tree: catalog
    args:
      uri: "sqlite:////mnt/data531/tiled/catalog.db"
      writable_storage:
        - '/mnt/data531/tiled/storage'
        - 'sqlite:////mnt/data531/tiled/tabular.db'
        - "/mnt"
      readable_storage:
        - "/mnt/data531/tiled/storage"
        - "/mnt"
      init_if_not_exists: true

# trees:
#   - path: /
#     tree: catalog
#     args:
#       uri: "sqlite:////mnt/data531/tiled/catalog2.db"
#       writable_storage:
#         - '/mnt/data531/tiled/storage'
#         - 'sqlite:////mnt/data531/tiled/tabular2.db'
#         - "/mnt"
#       readable_storage:
#         - "/mnt/data531/tiled/storage"
#         - "/mnt"
#       init_if_not_exists: true

streaming_cache:
  uri: redis://localhost:6379
